services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  InfiniteSoftware\Bundle\SuluArticlesPublisherBundle\:
    resource: '../../*'

  InfiniteSoftware\Bundle\SuluArticlesPublisherBundle\Command\ArticlesPublisherCommand:
    tags: ['console.command']